<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>UZonMail.ProPlugin</RootNamespace>
		<AssemblyName>UZonMail.ProPlugin</AssemblyName>
		<OutputType>Library</OutputType>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<BaseOutputPath>bin\x64\Debug</BaseOutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<BaseOutputPath>bin\x64\Release\</BaseOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="bin\**" />
		<Compile Remove="Controllers\EmailCrawler\Model\**" />
		<Compile Remove="Services\SystemInfo\**" />
		<Content Remove="bin\**" />
		<Content Remove="Controllers\EmailCrawler\Model\**" />
		<Content Remove="Services\SystemInfo\**" />
		<EmbeddedResource Remove="bin\**" />
		<EmbeddedResource Remove="Controllers\EmailCrawler\Model\**" />
		<EmbeddedResource Remove="Services\SystemInfo\**" />
		<None Remove="bin\**" />
		<None Remove="Controllers\EmailCrawler\Model\**" />
		<None Remove="Services\SystemInfo\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Services\License\PrivateKey.pem" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Services\License\PrivateKey.pem" />
	</ItemGroup>

	<ItemGroup>		
	  <PackageReference Include="DeviceId" Version="6.11.0" />		
	  <PackageReference Include="DnsClient" Version="1.8.0" />		
	  <PackageReference Include="Jint" Version="4.14.0" />		
	  <PackageReference Include="MathNet.Numerics" Version="5.0.0" />		
	  <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.10" />		
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\UzonMailCorePlugin\UzonMailCorePlugin.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Scripts\JS\a_bogus.js">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="Scripts\JS\x_bogus.js">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
