// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UzonMail.ProPlugin.SQL;

#nullable disable

namespace UzonMail.ProPlugin.Migrations.SqLite
{
    [DbContext(typeof(SqLiteContextPro))]
    [Migration("20260728111555_addInboxVerification")]
    partial class addInboxVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("EmailAnchorEmailVisitHistory", b =>
                {
                    b.Property<long>("EmailAnchorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VisitedHistoriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmailAnchorId", "VisitedHistoriesId");

                    b.HasIndex("VisitedHistoriesId");

                    b.ToTable("EmailAnchorEmailVisitHistory");
                });

            modelBuilder.Entity("EmailTemplateSendingGroup", b =>
                {
                    b.Property<long>("SendingGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TemplatesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SendingGroupId", "TemplatesId");

                    b.HasIndex("TemplatesId");

                    b.ToTable("EmailTemplateSendingGroup", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("FileUsageSendingGroup", b =>
                {
                    b.Property<long>("AttachmentsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SendingGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttachmentsId", "SendingGroupId");

                    b.HasIndex("SendingGroupId");

                    b.ToTable("FileUsageSendingGroup", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("OutboxSendingGroup", b =>
                {
                    b.Property<long>("OutboxesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SendingGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OutboxesId", "SendingGroupId");

                    b.HasIndex("SendingGroupId");

                    b.ToTable("OutboxSendingGroup", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PermissionCodeRole", b =>
                {
                    b.Property<long>("PermissionCodesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RolesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PermissionCodesId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("PermissionCodeRole", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("RoleUserRoles", b =>
                {
                    b.Property<long>("RolesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserRolesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolesId", "UserRolesId");

                    b.HasIndex("UserRolesId");

                    b.ToTable("RoleUserRoles", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Base.IdAndName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.HasKey("Id");

                    b.ToTable("IdAndName", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.EmailSending.EmailAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.HasKey("Id");

                    b.ToTable("EmailAddress", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.EmailSending.SendingGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BccBoxes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("CcBoxes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("InboxGroups")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inboxes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InboxesCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDistributed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<string>("OutboxGroups")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutboxesCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("ProxyIds")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResumeAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SendEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SendStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SendingType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SentCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subjects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ResumeAtUtc", "Id");

                    b.ToTable("SendingGroup", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Emails.Outbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionSecurity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EmailGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinkCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSendCountPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProxyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToEmails")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("SentCountDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SentTotalToday")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidFailReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "EmailGroupId", "IsValid", "Id");

                    b.ToTable("Outbox", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Files.FileBucket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<string>("RootDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileBucket", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Files.FileCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Sort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ParentId");

                    b.ToTable("FileCategory", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Files.FileObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileBucketId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileBucketId");

                    b.ToTable("FileObject", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Files.FileUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayNameKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReferenceCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FileObjectId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("FileUsage", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Organization.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long?>("EmailTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("Department", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Organization.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EmailTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystsemUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("User", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Permission.PermissionCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNegative")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PermissionCode", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Permission.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionCodesCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Permission.UserRoles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserRoles", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Templates.EmailTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplate", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.ApiAccess.AccessToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AccessTokens");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.EmailCrawler.CrawlerTaskInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("OutboxGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProxyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TikTokDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CrawlerTaskInfos");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.EmailCrawler.CrawlerTaskResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CrawlerTaskInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExistExtraInfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAttachingInbox")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("TikTokAuthorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TikTokAuthorId");

                    b.ToTable("CrawlerTaskResults");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.EmailCrawler.TikTokAuthorDiversification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiversificationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("TikTokAuthorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TikTokAuthorDiversifications");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.EmailCrawler.TikTokDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<string>("OdinId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TikTokDevices");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.EmailCrawler.TiktokAuthor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarLarger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarMedium")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarThumb")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CommentSetting")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CrawledCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiggCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownloadSetting")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DueSetting")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<long>("FollowingAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FollwerCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FollwingCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FreindCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ftc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Heart")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HeartCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instagram")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdVirtual")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmbedBanned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsParsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<bool>("OpenFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PrivateAccount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Relation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Secret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Signature")
                        .HasColumnType("TEXT");

                    b.Property<int>("StitchSetting")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telegram")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TtSeller")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VideoCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Youtube")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiktokAuthors");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.EmailVerify.InboxVerificationSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanConnectSmtp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFullInbox")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsB2C")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCatchAll")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeliverable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisposable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRoleAccount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValidSyntax")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MxDomainCacheId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyntaxDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyntaxSuggestion")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyntaxUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MxDomainCacheId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("InboxVerificationSnapshots");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.EmailVerify.MxDomainCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptsMail")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("MxDomainCaches");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.EmailVerify.MxDomainRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MxDomainCacheId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MxDomainCacheId");

                    b.ToTable("MxDomainRecords");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.IPWarmUp.IpWarmUpUpPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AttachmentIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("BccIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("CcIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("InboxIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.PrimitiveCollection<string>("OutboxIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SendCountChartPoints")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Subjects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TasksCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("TemplateIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IpWarmUpUpPlans");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.IPWarmUp.IpWarmUpUpTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("IPWarmUpPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InboxesCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<int>("OutboxesCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SendingGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IPWarmUpPlanId");

                    b.ToTable("IpWarmUpUpTasks");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.JsVariable.JsFunctionDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("JsFunctionDefinitions");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.JsVariable.JsVariableSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JsVariableSources");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.ReadingTracker.EmailAnchor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstVisitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InboxEmails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastVisitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<string>("OutboxEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SendingGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SendingItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VisitedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EmailAnchors");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.ReadingTracker.EmailVisitHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.HasKey("Id");

                    b.ToTable("EmailVisitHistories");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.ReadingTracker.IPInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISP")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IP");

                    b.ToTable("IPInfos");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.Unsubscribes.UnsubscribeButton", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ButtonHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UnsubscribeButtons");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.Unsubscribes.UnsubscribeEmail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Email");

                    b.ToTable("UnsubscribeEmails");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.Unsubscribes.UnsubscribePage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UnsubscribePages");
                });

            modelBuilder.Entity("EmailAnchorEmailVisitHistory", b =>
                {
                    b.HasOne("UzonMail.ProPlugin.SQL.ReadingTracker.EmailAnchor", null)
                        .WithMany()
                        .HasForeignKey("EmailAnchorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzonMail.ProPlugin.SQL.ReadingTracker.EmailVisitHistory", null)
                        .WithMany()
                        .HasForeignKey("VisitedHistoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmailTemplateSendingGroup", b =>
                {
                    b.HasOne("UzonMail.DB.SQL.Core.EmailSending.SendingGroup", null)
                        .WithMany()
                        .HasForeignKey("SendingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzonMail.DB.SQL.Core.Templates.EmailTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FileUsageSendingGroup", b =>
                {
                    b.HasOne("UzonMail.DB.SQL.Core.Files.FileUsage", null)
                        .WithMany()
                        .HasForeignKey("AttachmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzonMail.DB.SQL.Core.EmailSending.SendingGroup", null)
                        .WithMany()
                        .HasForeignKey("SendingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OutboxSendingGroup", b =>
                {
                    b.HasOne("UzonMail.DB.SQL.Core.Emails.Outbox", null)
                        .WithMany()
                        .HasForeignKey("OutboxesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzonMail.DB.SQL.Core.EmailSending.SendingGroup", null)
                        .WithMany()
                        .HasForeignKey("SendingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionCodeRole", b =>
                {
                    b.HasOne("UzonMail.DB.SQL.Core.Permission.PermissionCode", null)
                        .WithMany()
                        .HasForeignKey("PermissionCodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzonMail.DB.SQL.Core.Permission.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUserRoles", b =>
                {
                    b.HasOne("UzonMail.DB.SQL.Core.Permission.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzonMail.DB.SQL.Core.Permission.UserRoles", null)
                        .WithMany()
                        .HasForeignKey("UserRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Files.FileCategory", b =>
                {
                    b.HasOne("UzonMail.DB.SQL.Core.Organization.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzonMail.DB.SQL.Core.Files.FileCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("OwnerUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Files.FileObject", b =>
                {
                    b.HasOne("UzonMail.DB.SQL.Core.Files.FileBucket", "FileBucket")
                        .WithMany()
                        .HasForeignKey("FileBucketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileBucket");
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Files.FileUsage", b =>
                {
                    b.HasOne("UzonMail.DB.SQL.Core.Files.FileCategory", "Category")
                        .WithMany("FileUsages")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzonMail.DB.SQL.Core.Files.FileObject", "FileObject")
                        .WithMany()
                        .HasForeignKey("FileObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzonMail.DB.SQL.Core.Organization.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FileObject");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Organization.Department", b =>
                {
                    b.HasOne("UzonMail.DB.SQL.Core.Templates.EmailTemplate", null)
                        .WithMany("ShareToOrganizations")
                        .HasForeignKey("EmailTemplateId");
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Organization.User", b =>
                {
                    b.HasOne("UzonMail.DB.SQL.Core.Templates.EmailTemplate", null)
                        .WithMany("ShareToUsers")
                        .HasForeignKey("EmailTemplateId");
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Permission.UserRoles", b =>
                {
                    b.HasOne("UzonMail.DB.SQL.Core.Organization.User", "User")
                        .WithOne("UserRoles")
                        .HasForeignKey("UzonMail.DB.SQL.Core.Permission.UserRoles", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.EmailCrawler.CrawlerTaskResult", b =>
                {
                    b.HasOne("UzonMail.ProPlugin.SQL.EmailCrawler.TiktokAuthor", "TiktokAuthor")
                        .WithMany()
                        .HasForeignKey("TikTokAuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TiktokAuthor");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.EmailVerify.InboxVerificationSnapshot", b =>
                {
                    b.HasOne("UzonMail.ProPlugin.SQL.EmailVerify.MxDomainCache", "MxDomainCache")
                        .WithMany()
                        .HasForeignKey("MxDomainCacheId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MxDomainCache");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.EmailVerify.MxDomainRecord", b =>
                {
                    b.HasOne("UzonMail.ProPlugin.SQL.EmailVerify.MxDomainCache", "MxDomainCache")
                        .WithMany("Records")
                        .HasForeignKey("MxDomainCacheId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MxDomainCache");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.IPWarmUp.IpWarmUpUpTask", b =>
                {
                    b.HasOne("UzonMail.ProPlugin.SQL.IPWarmUp.IpWarmUpUpPlan", "IPWarmUpPlan")
                        .WithMany()
                        .HasForeignKey("IPWarmUpPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("IPWarmUpPlan");
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Files.FileCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("FileUsages");
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Organization.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UzonMail.DB.SQL.Core.Templates.EmailTemplate", b =>
                {
                    b.Navigation("ShareToOrganizations");

                    b.Navigation("ShareToUsers");
                });

            modelBuilder.Entity("UzonMail.ProPlugin.SQL.EmailVerify.MxDomainCache", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
