using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using UzonMail.ProPlugin.SQL;

namespace UzonMail.ProPlugin.Migrations.PostgreSQL;

[DbContext(typeof(PostgreSqlContextPro))]
[Migration("20260727120003_addInboxVerification")]
public sealed class addInboxVerification : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE "MxDomainCaches" (
              "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Domain" text NOT NULL UNIQUE,
              "AcceptsMail" boolean NOT NULL, "FailureReason" text NULL, "CheckedAtUtc" timestamp with time zone NOT NULL,
              "ExpiresAtUtc" timestamp with time zone NOT NULL, "_id" text NOT NULL, "CreateDate" timestamp with time zone NOT NULL,
              "IsDeleted" boolean NOT NULL, "IsHidden" boolean NOT NULL);
            CREATE TABLE "MxDomainRecords" (
              "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "MxDomainCacheId" bigint NOT NULL REFERENCES "MxDomainCaches"("Id"),
              "Host" text NOT NULL, "Priority" integer NOT NULL, "_id" text NOT NULL, "CreateDate" timestamp with time zone NOT NULL,
              "IsDeleted" boolean NOT NULL, "IsHidden" boolean NOT NULL);
            CREATE INDEX "IX_MxDomainRecords_MxDomainCacheId" ON "MxDomainRecords" ("MxDomainCacheId");
            CREATE TABLE "InboxVerificationSnapshots" (
              "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "NormalizedEmail" text NOT NULL,
              "State" integer NOT NULL, "FailureReason" text NULL, "VerifiedAtUtc" timestamp with time zone NOT NULL,
              "ExpiresAtUtc" timestamp with time zone NOT NULL, "SyntaxDomain" text NULL, "SyntaxUsername" text NULL,
              "SyntaxSuggestion" text NULL, "IsValidSyntax" boolean NOT NULL, "IsDisposable" boolean NOT NULL,
              "IsRoleAccount" boolean NOT NULL, "IsB2C" boolean NOT NULL, "MxDomainCacheId" bigint NULL REFERENCES "MxDomainCaches"("Id"),
              "CanConnectSmtp" boolean NOT NULL, "HasFullInbox" boolean NOT NULL, "IsCatchAll" boolean NOT NULL,
              "IsDeliverable" boolean NOT NULL, "IsDisabled" boolean NOT NULL, "_id" text NOT NULL,
              "CreateDate" timestamp with time zone NOT NULL, "IsDeleted" boolean NOT NULL, "IsHidden" boolean NOT NULL);
            CREATE UNIQUE INDEX "IX_InboxVerificationSnapshots_NormalizedEmail" ON "InboxVerificationSnapshots" ("NormalizedEmail");
            CREATE INDEX "IX_InboxVerificationSnapshots_MxDomainCacheId" ON "InboxVerificationSnapshots" ("MxDomainCacheId");
            """
        );
    }

    protected override void Down(MigrationBuilder migrationBuilder) =>
        migrationBuilder.Sql(
            "DROP TABLE \"InboxVerificationSnapshots\"; DROP TABLE \"MxDomainRecords\"; DROP TABLE \"MxDomainCaches\";"
        );
}
