// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UZonMail.ProPlugin.SQL;

#nullable disable

namespace UZonMail.ProPlugin.Migrations.Mysql
{
    [DbContext(typeof(MySqlContextPro))]
    [Migration("20250523042320_addJsVariable")]
    partial class addJsVariable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UZonMailProPlugin.SQL.EmailCrawler.CrawlerTaskInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OutboxGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProxyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TikTokDeviceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CrawlerTaskInfos");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.EmailCrawler.CrawlerTaskResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CrawlerTaskInfoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ExistExtraInfo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAttachingInbox")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("TikTokAuthorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TikTokAuthorId");

                    b.ToTable("CrawlerTaskResults");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.EmailCrawler.TikTokAuthorDiversification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DiversificationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("TikTokAuthorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TikTokAuthorDiversifications");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.EmailCrawler.TikTokDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsShared")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<string>("OdinId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TikTokDevices");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.EmailCrawler.TiktokAuthor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarLarger")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AvatarMedium")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AvatarThumb")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CommentSetting")
                        .HasColumnType("int");

                    b.Property<long>("CrawledCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DiggCount")
                        .HasColumnType("bigint");

                    b.Property<int>("DownloadSetting")
                        .HasColumnType("int");

                    b.Property<int>("DueSetting")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<long>("FollowingAuthorId")
                        .HasColumnType("bigint");

                    b.Property<long>("FollwerCount")
                        .HasColumnType("bigint");

                    b.Property<long>("FollwingCount")
                        .HasColumnType("bigint");

                    b.Property<long>("FreindCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("Ftc")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("Heart")
                        .HasColumnType("bigint");

                    b.Property<long>("HeartCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Instagram")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdVirtual")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmbedBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsParsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<bool>("OpenFavorite")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<bool>("PrivateAccount")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Relation")
                        .HasColumnType("int");

                    b.Property<string>("SecUid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Secret")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Signature")
                        .HasColumnType("longtext");

                    b.Property<int>("StitchSetting")
                        .HasColumnType("int");

                    b.Property<string>("Telegram")
                        .HasColumnType("longtext");

                    b.Property<bool>("TtSeller")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Verified")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("VideoCount")
                        .HasColumnType("bigint");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("longtext");

                    b.Property<string>("Youtube")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TiktokAuthors");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.JsVariable.JsFunctionDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FunctionBody")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("JsFunctionDefinitions");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.JsVariable.JsVariableSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("JsVariableSources");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.ReadingTracker.EmailAnchor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FirstVisitDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InboxEmails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastVisitDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<string>("OutboxEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("SendingGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("SendingItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("VisitedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmailAnchors");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.ReadingTracker.EmailVisitHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("EmailAnchorId")
                        .HasColumnType("bigint");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.HasKey("Id");

                    b.HasIndex("EmailAnchorId");

                    b.ToTable("EmailVisitHistories");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.ReadingTracker.IPInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ISP")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Latitude")
                        .HasColumnType("longtext");

                    b.Property<string>("Longitude")
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<string>("TimeZone")
                        .HasColumnType("longtext");

                    b.Property<string>("UsageType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IP");

                    b.ToTable("IPInfos");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.Unsubscribes.UnsubscribeButton", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ButtonHtml")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UnsubscribeButtons");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.Unsubscribes.UnsubscribeEmail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Host")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Email");

                    b.ToTable("UnsubscribeEmails");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.Unsubscribes.UnsubscribePage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("_id");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UnsubscribePages");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.EmailCrawler.CrawlerTaskResult", b =>
                {
                    b.HasOne("UZonMailProPlugin.SQL.EmailCrawler.TiktokAuthor", "TiktokAuthor")
                        .WithMany()
                        .HasForeignKey("TikTokAuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TiktokAuthor");
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.ReadingTracker.EmailVisitHistory", b =>
                {
                    b.HasOne("UZonMailProPlugin.SQL.ReadingTracker.EmailAnchor", null)
                        .WithMany("VisitedHistories")
                        .HasForeignKey("EmailAnchorId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("UZonMailProPlugin.SQL.ReadingTracker.EmailAnchor", b =>
                {
                    b.Navigation("VisitedHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
